FROM ubuntu:latest
ENTRYPOINT /app
RUN apt update && apt install -y git nodejs npm
RUN git clone https://github.com/unlimish/Headgear.git .
RUN npm install
CMD ["sh", "-c", "node deploy-commands.js && node index.js"]
