services:
  headgear:
    image: headgear-zu2
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - headgear_data:/app/data
      - ./logs:/app/logs
    command: sh -c "cd /app/ && node deploy-commands.js && node index.js"
    restart: always
    networks:
      - discord_network

volumes:
  headgear_data:

networks:
  discord_network:
    driver: bridge
